apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s3manager
  namespace: majako-services
spec:
  selector:
    matchLabels:
      app: s3manager # must match .spec.template.metadata.labels
  replicas: 1
  serviceName: "s3manager"
  template:
    metadata:
      labels:
        app: s3manager
    spec:
      containers:
      - name: s3manager
        image: registry.digitalocean.com/majako/s3manager:<TAG>
        envFrom:
          - secretRef:
              name: s3manager-environment
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 1250Mi
          limits:
            memory: 1250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: s3manager
  namespace: majako-services
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: s3manager
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3manager
  namespace: majako-services
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300s"
spec:
  tls:
  - hosts:
    - s3manager.majako.net
    secretName: s3manager.majako.net-tls
  rules:
  - host: s3manager.majako.net
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: s3manager
              port:
                number: 8080
